﻿﻿useclient

import{useState,useEffect}fromreact
importLinkfromnext/link
importHeaderfrom@/components/Header

interfaceWeight{id:string;weight_grams:number;notes:string|null;measured_at:string}

exportdefaultfunctionGewichtPage(){
const[weights,setWeights]=useState<Weight[]>([])
const[loading,setLoading]=useState(true)
const[showForm,setShowForm]=useState(false)
const[grams,setGrams]=useState()
const[notes,setNotes]=useState()
const[saving,setSaving]=useState(false)

useEffect(()=>{load()},[])

constload=async()=>{
setLoading(true)
constres=awaitfetch(/api/weight)
constdata=awaitres.json()
setWeights(data.weights??[])
setLoading(false)
}

constsave=async()=>{
if(!grams)return
setSaving(true)
awaitfetch(/api/weight,{
method:POST,
headers:{Content-Type:application/json},
body:JSON.stringify({weight_grams:parseInt(grams),notes:notes||null,measured_at:newDate().toISOString()}),
})
setGrams();setNotes();setShowForm(false)
awaitload()
setSaving(false)
}

constdel=async(id:string)=>{
if(!confirm(Eintraglöschen?))return
awaitfetch(/api/weight,{method:DELETE,headers:{Content-Type:application/json},body:JSON.stringify({id})})
awaitload()
}

//Chart:last15weightsreversed(oldestfirst)
constchartData=[...weights].reverse().slice(-15)
constmaxG=Math.max(...chartData.map(w=>w.weight_grams),1)
constminG=Math.min(...chartData.map(w=>w.weight_grams),maxG)
constrange=maxG-minG||100

//Trend
consttrend=weights.length>=2
?weights[0].weight_grams-weights[Math.min(weights.length-1,4)].weight_grams
:0
consttrendLabel=trend>50?`²+${(trend/1000).toFixed(2)}kg`:trend<-50?`¼${(trend/1000).toFixed(2)}kg`:†’Stabil
consttrendColor=trend>100?text-red-500:trend<-100?text-orange-500:text-green-600

constlatest=weights[0]

return(
<divclassName="min-h-screen">
<Header/>
<mainclassName="max-w-2xlmx-autopx-4py-6">
<divclassName="flexitems-centerjustify-betweenmb-6">
<divclassName="flexitems-centergap-3">
<Linkhref="/dashboard"className="text-gray-400hover:text-gray-600">†Zurück</Link>
<h1className="text-xlfont-boldtext-gray-800">ï¸Gewichtsverlauf</h1>
</div>
<buttononClick={()=>setShowForm(s=>!s)}className="btn-primarytext-sm">+Wiegen</button>
</div>

{/*Quickentry*/}
{showForm&&(
<divclassName="cardp-4mb-4">
<pclassName="font-semiboldtext-gray-800mb-3">NeuesGewicht</p>
<divclassName="flexgap-3mb-3">
<divclassName="flex-1">
<labelclassName="label">GewichtinGramm*</label>
<input
type="number"
value={grams}
onChange={e=>setGrams(e.target.value)}
placeholder="z.B.4200"
className="input-field"
autoFocus
/>
</div>
</div>
<divclassName="mb-3">
<labelclassName="label">Notiz(optional)</label>
<inputtype="text"value={notes}onChange={e=>setNotes(e.target.value)}placeholder="z.B.nachdemFressen"className="input-field"/>
</div>
<divclassName="flexgap-2">
<buttononClick={()=>setShowForm(false)}className="btn-secondary">Abbrechen</button>
<buttononClick={save}disabled={!grams||saving}className="btn-primary">{saving?Speichern:Speichern}</button>
</div>
</div>
)}

{/*Currentweightcard*/}
{latest&&(
<divclassName="cardp-5mb-4bg-gradient-to-brfrom-amber-50to-amber-100borderborder-amber-200">
<divclassName="flexitems-centerjustify-between">
<div>
<pclassName="text-xstext-amber-600font-semibolduppercasetracking-widemb-1">AktuellesGewicht</p>
<pclassName="text-4xlfont-blacktext-gray-800">{(latest.weight_grams/1000).toFixed(2)}<spanclassName="text-xlfont-normaltext-gray-500">kg</span></p>
<pclassName="text-smtext-gray-500mt-1">{newDate(latest.measured_at).toLocaleDateString(de-DE,{day:numeric,month:long,year:numeric})}</p>
</div>
<divclassName="text-right">
<pclassName="text-xstext-gray-500mb-1">Trend(letzte5)</p>
<pclassName={`text-lgfont-bold${trendColor}`}>{trendLabel}</p>
</div>
</div>
</div>
)}

{/*Chart*/}
{chartData.length>=2&&(
<divclassName="cardp-5mb-4">
<pclassName="font-semiboldtext-gray-800mb-4">Verlauf</p>
<divclassName="flexitems-endgap-1.5h-28">
{chartData.map((w,i)=>{
consth=((w.weight_grams-minG)/range)*80+20
constisLatest=i===chartData.length-1
return(
<divkey={w.id}className="flex-1flexflex-colitems-centergap-1">
<spanclassName="text-[8px]text-gray-400">{(w.weight_grams/1000).toFixed(1)}</span>
<div
className={`w-fullrounded-ttransition-all${isLatest?bg-amber-500:bg-amber-200}`}
style={{height:h}}
/>
<spanclassName="text-[8px]text-gray-400rotate-0">
{newDate(w.measured_at).toLocaleDateString(de-DE,{day:2-digit,month:2-digit})}
</span>
</div>
)
})}
</div>
<divclassName="flexjustify-betweentext-xstext-gray-400mt-1">
<span>{(minG/1000).toFixed(2)}kg</span>
<span>{(maxG/1000).toFixed(2)}kg</span>
</div>
</div>
)}

{/*List*/}
<divclassName="cardp-4">
<pclassName="font-semiboldtext-gray-800mb-3">AlleEinträge</p>
{loading?(
<divclassName="space-y-2">{Array.from({length:4}).map((_,i)=><divkey={i}className="h-10bg-gray-100rounded-xlanimate-pulse"/>)}</div>
):weights.length===0?(
<pclassName="text-gray-400text-smtext-centerpy-6">NochkeinGewichteingetragen.WiegeJoschiundtippeaufž+Wiegen".</p>
):(
<divclassName="space-y-2">
{weights.map((w,i)=>(
<divkey={w.id}className="flexitems-centerjustify-betweenpy-2border-bborder-gray-50last:border-0">
<div>
<spanclassName={`font-bold${i===0?text-amber-600:text-gray-700}`}>{(w.weight_grams/1000).toFixed(3)}kg</span>
{w.notes&&<spanclassName="text-xstext-gray-400ml-2">{w.notes}</span>}
</div>
<divclassName="flexitems-centergap-3">
<spanclassName="text-xstext-gray-400">{newDate(w.measured_at).toLocaleDateString(de-DE,{day:2-digit,month:2-digit,year:2-digit})}</span>
<buttononClick={()=>del(w.id)}className="text-gray-300hover:text-red-400text-smtransition-colors"></button>
</div>
</div>
))}
</div>
)}
</div>
</main>
</div>
)
}
