﻿﻿useclient

import{useEffect,useState}fromreact
importHeaderfrom@/components/Header
import{ANIFIT_FOODS,getFoodInfo,getProteinLabel,getProteinBadgeColor}from@/lib/food-data
importtype{PantryItem}from@/lib/types

functionRestockLabel({date}:{date:string|null}){
if(!date)returnnull
constd=newDate(date)
consttoday=newDate();today.setHours(0,0,0,0)
constdiff=Math.ceil((d.getTime()-today.getTime())/(1000*60*60*24))
if(diff<0)return<spanclassName="text-xstext-gray-400">Nachschubüberfällig</span>
if(diff===0)return<spanclassName="text-xstext-green-600font-medium">Nachschubheute</span>
if(diff<=3)return<spanclassName="text-xstext-amber-600">Nachschubin{diff}Tag{diff>1?en:}</span>
return<spanclassName="text-xstext-gray-400">Nachschub{d.toLocaleDateString(de-DE,{day:numeric,month:short})}</span>
}

exportdefaultfunctionPantryPage(){
const[items,setItems]=useState<PantryItem[]>([])
const[loading,setLoading]=useState(true)
const[showAdd,setShowAdd]=useState(false)
const[addBrand,setAddBrand]=useState(Anifit)
const[addType,setAddType]=useState()
const[addQty,setAddQty]=useState(1)
const[addRestock,setAddRestock]=useState()
const[saving,setSaving]=useState(false)
const[editRestockId,setEditRestockId]=useState<string|null>(null)
const[editRestockDate,setEditRestockDate]=useState()

useEffect(()=>{
fetch(/api/pantry).then(r=>r.json()).then(d=>{
setItems(d.items??[])
setLoading(false)
})
},[])

constupdateQty=async(id:string,delta:number)=>{
constitem=items.find(i=>i.id===id)
if(!item)return
constnewQty=Math.max(0,item.quantity+delta)
setItems(prev=>prev.map(i=>i.id===id?{...i,quantity:newQty}:i))
awaitfetch(/api/pantry,{
method:PATCH,
headers:{Content-Type:application/json},
body:JSON.stringify({id,quantity:newQty}),
})
}

constdeleteItem=async(id:string)=>{
setItems(prev=>prev.filter(i=>i.id!==id))
awaitfetch(/api/pantry,{
method:DELETE,
headers:{Content-Type:application/json},
body:JSON.stringify({id}),
})
}

constsaveRestock=async(id:string)=>{
setItems(prev=>prev.map(i=>i.id===id?{...i,restock_date:editRestockDate||null}:i))
awaitfetch(/api/pantry,{
method:PATCH,
headers:{Content-Type:application/json},
body:JSON.stringify({id,restock_date:editRestockDate||null}),
})
setEditRestockId(null)
}

constaddItem=async()=>{
if(!addType)return
setSaving(true)
constres=awaitfetch(/api/pantry,{
method:POST,
headers:{Content-Type:application/json},
body:JSON.stringify({brand:addBrand,type:addType,quantity:addQty,restock_date:addRestock||null}),
})
constdata=awaitres.json()
if(data.item)setItems(prev=>[...prev,data.item])
setShowAdd(false)
setAddType()
setAddQty(1)
setAddRestock()
setSaving(false)
}

//Anifit-SortendienochnichtimVorratsind
constexistingKeys=newSet(items.map(i=>`${i.brand}||${i.type}`))
constavailableToAdd=ANIFIT_FOODS.filter(f=>!existingKeys.has(`${f.brand}||${f.type}`))

constinStock=items.filter(i=>i.quantity>0)
constoutOfStock=items.filter(i=>i.quantity===0)

return(
<divclassName="min-h-screen">
<Header/>
<mainclassName="max-w-2xlmx-autopx-4py-5space-y-4pb-8">

<divclassName="flexitems-centerjustify-between">
<div>
<h1className="text-xlfont-boldtext-gray-800">Vorrat</h1>
<pclassName="text-xstext-gray-400mt-0.5">WasistaktuellimHaus?</p>
</div>
<button
onClick={()=>setShowAdd(true)}
className="text-smfont-mediumtext-whitebg-amber-500hover:bg-amber-600px-4py-2rounded-xltransition-colors"
>
+Hinzufügen
</button>
</div>

{loading&&(
<divclassName="space-y-3animate-pulse">
{[1,2,3].map(i=><divkey={i}className="h-20bg-whiterounded-2xlborderborder-gray-100"/>)}
</div>
)}

{!loading&&inStock.length===0&&(
<divclassName="bg-whiterounded-2xlborderborder-gray-100p-6text-center">
<pclassName="text-gray-400text-sm">NochkeinFutterimVorrat</p>
<pclassName="text-gray-300text-xsmt-1">Tippeauf"+Hinzufügen"umanzufangen</p>
</div>
)}

{/*ImVorrat*/}
{inStock.length>0&&(
<divclassName="space-y-2">
{inStock.map(item=>{
constinfo=getFoodInfo(item.brand,item.type)
return(
<divkey={item.id}className="cardoverflow-hidden">
<divclassName="px-4py-3flexitems-startgap-3">
<divclassName="flex-1min-w-0">
<divclassName="flexitems-centergap-2flex-wrap">
<spanclassName="text-smfont-mediumtext-gray-800">{item.type||item.brand}</span>
{info&&(
<spanclassName={`text-[10px]font-semiboldpx-2py-0.5rounded-full${getProteinBadgeColor(info)}`}>
{getProteinLabel(info)}
</span>
)}
</div>
{info?.notes&&(
<pclassName="text-xstext-gray-400mt-0.5">{info.notes}</p>
)}
<divclassName="flexitems-centergap-2mt-1">
{editRestockId===item.id?(
<divclassName="flexitems-centergap-1.5">
<input
type="date"
value={editRestockDate}
onChange={e=>setEditRestockDate(e.target.value)}
className="text-xsborderborder-gray-200rounded-lgpx-2py-1"
/>
<buttononClick={()=>saveRestock(item.id)}className="text-xstext-amber-600font-medium">OK</button>
<buttononClick={()=>setEditRestockId(null)}className="text-xstext-gray-400"></button>
</div>
):(
<button
onClick={()=>{setEditRestockId(item.id);setEditRestockDate(item.restock_date??)}}
className="flexitems-centergap-1"
>
{item.restock_date
?<RestockLabeldate={item.restock_date}/>
:<spanclassName="text-xstext-gray-300hover:text-gray-400">+Nachschub-Datum</span>
}
</button>
)}
</div>
</div>

{/*Mengestepper*/}
<divclassName="flexitems-centergap-2flex-shrink-0">
<button
onClick={()=>updateQty(item.id,-1)}
className="w-8h-8rounded-fullbg-gray-100hover:bg-gray-200text-gray-600text-lgfont-mediumflexitems-centerjustify-centerleading-none"
>
ˆ’
</button>
<spanclassName="text-smfont-boldtext-gray-800w-5text-center">{item.quantity}</span>
<button
onClick={()=>updateQty(item.id,+1)}
className="w-8h-8rounded-fullbg-amber-100hover:bg-amber-200text-amber-700text-lgfont-mediumflexitems-centerjustify-centerleading-none"
>
+
</button>
</div>
</div>
</div>
)
})}
</div>
)}

{/*Leer/aufgebraucht*/}
{outOfStock.length>0&&(
<div>
<pclassName="text-xsfont-semiboldtext-gray-400uppercasetracking-widepx-1mb-2">Aufgebraucht</p>
<divclassName="space-y-2">
{outOfStock.map(item=>(
<divkey={item.id}className="bg-whiterounded-2xlborderborder-gray-100opacity-50overflow-hidden">
<divclassName="px-4py-3flexitems-centergap-3">
<divclassName="flex-1min-w-0">
<pclassName="text-smtext-gray-500line-through">{item.type||item.brand}</p>
<RestockLabeldate={item.restock_date}/>
</div>
<divclassName="flexitems-centergap-2">
<button
onClick={()=>updateQty(item.id,+1)}
className="text-xstext-amber-600font-mediumbg-amber-50px-3py-1.5rounded-lg"
>
Nachgefüllt
</button>
<button
onClick={()=>deleteItem(item.id)}
className="text-xstext-gray-300hover:text-red-400transition-colorspx-1"
>

</button>
</div>
</div>
</div>
))}
</div>
</div>
)}

</main>

{/*AddModal*/}
{showAdd&&(
<divclassName="fixedinset-0bg-black/40z-50flexitems-endsm:items-centerjustify-centerp-4"onClick={()=>setShowAdd(false)}>
<divclassName="bg-whiterounded-3xlw-fullmax-w-mdshadow-xl"onClick={e=>e.stopPropagation()}>
<divclassName="px-5pt-5pb-2">
<h2className="text-lgfont-boldtext-gray-800">Futterhinzufügen</h2>
</div>

<divclassName="px-5py-3space-y-4">
{/*Sortewählenausnicht-vorhandenenAnifit-Sorten*/}
<div>
<labelclassName="text-xsfont-semiboldtext-gray-500uppercasetracking-wideblockmb-2">Anifit-Sorte</label>
<divclassName="space-y-1.5max-h-64overflow-y-auto">
{availableToAdd.map(f=>(
<button
key={f.type}
onClick={()=>{setAddBrand(f.brand);setAddType(f.type)}}
className={`w-fulltext-leftpx-3py-2.5rounded-xlbordertransition-colors${
addType===f.type
?border-amber-400bg-amber-50
:border-gray-100hover:border-gray-200bg-gray-50
}`}
>
<divclassName="flexitems-centerjustify-between">
<spanclassName="text-smtext-gray-800">{f.type}</span>
<spanclassName={`text-[10px]font-semiboldpx-2py-0.5rounded-full${getProteinBadgeColor(f)}`}>
{f.proteinType===mono?Mono:Multi}
</span>
</div>
<pclassName="text-[11px]text-gray-400mt-0.5">{f.proteins.join(+)}</p>
</button>
))}
{availableToAdd.length===0&&(
<pclassName="text-smtext-gray-400text-centerpy-4">AlleAnifit-SortenbereitsimVorrat</p>
)}
</div>
</div>

<div>
<labelclassName="text-xsfont-semiboldtext-gray-500uppercasetracking-wideblockmb-2">AnzahlDosen</label>
<divclassName="flexitems-centergap-3">
<buttononClick={()=>setAddQty(q=>Math.max(1,q-1))}className="w-10h-10rounded-fullbg-gray-100text-gray-600text-xlfont-mediumflexitems-centerjustify-center">ˆ’</button>
<spanclassName="text-2xlfont-boldtext-gray-800w-8text-center">{addQty}</span>
<buttononClick={()=>setAddQty(q=>q+1)}className="w-10h-10rounded-fullbg-amber-100text-amber-700text-xlfont-mediumflexitems-centerjustify-center">+</button>
</div>
</div>

<div>
<labelclassName="text-xsfont-semiboldtext-gray-500uppercasetracking-wideblockmb-1.5">Nachschuberwartetam</label>
<input
type="date"
value={addRestock}
onChange={e=>setAddRestock(e.target.value)}
className="w-fullborderborder-gray-200rounded-xlpx-3py-2.5text-smfocus:outline-nonefocus:ring-2focus:ring-amber-300"
/>
</div>
</div>

<divclassName="px-5pb-5flexgap-2">
<buttononClick={()=>setShowAdd(false)}className="flex-1py-3rounded-xlborderborder-gray-200text-gray-600text-smfont-medium">
Abbrechen
</button>
<button
onClick={addItem}
disabled={!addType||saving}
className="flex-1py-3rounded-xlbg-amber-500text-whitetext-smfont-semibolddisabled:opacity-40hover:bg-amber-600transition-colors"
>
{saving?Speichern:Hinzufügen}
</button>
</div>
</div>
</div>
)}
</div>
)
}
