﻿﻿useclient

import{useState,useEffect}fromreact
importLinkfromnext/link
importHeaderfrom@/components/Header

interfaceMedication{
id:string;name:string;dosage:string|null;frequency:string|null
start_date:string|null;end_date:string|null;notes:string|null;active:boolean
}

constFREQUENCIES=[1täglich,2täglich,3täglich,Jeden2.Tag,1wöchentlich,NachBedarf]

exportdefaultfunctionMedikamentePage(){
const[meds,setMeds]=useState<Medication[]>([])
const[loading,setLoading]=useState(true)
const[showForm,setShowForm]=useState(false)
const[saving,setSaving]=useState(false)
const[form,setForm]=useState({name:,dosage:,frequency:,start_date:,end_date:,notes:})

useEffect(()=>{load()},[])

constload=async()=>{
setLoading(true)
constres=awaitfetch(/api/medications)
constdata=awaitres.json()
setMeds(data.medications??[])
setLoading(false)
}

constsave=async()=>{
if(!form.name)return
setSaving(true)
awaitfetch(/api/medications,{
method:POST,
headers:{Content-Type:application/json},
body:JSON.stringify({...form,active:true}),
})
setForm({name:,dosage:,frequency:,start_date:,end_date:,notes:})
setShowForm(false)
awaitload()
setSaving(false)
}

consttoggle=async(med:Medication)=>{
awaitfetch(/api/medications,{
method:PATCH,
headers:{Content-Type:application/json},
body:JSON.stringify({id:med.id,active:!med.active}),
})
awaitload()
}

constdel=async(id:string)=>{
if(!confirm(Medikamentlöschen?))return
awaitfetch(/api/medications,{method:DELETE,headers:{Content-Type:application/json},body:JSON.stringify({id})})
awaitload()
}

constactive=meds.filter(m=>m.active)
constinactive=meds.filter(m=>!m.active)

constMedCard=({med}:{med:Medication})=>(
<divclassName={`cardp-4${med.active?border-l-4border-l-green-400:opacity-60}`}>
<divclassName="flexitems-startjustify-betweengap-3">
<divclassName="flex-1min-w-0">
<divclassName="flexitems-centergap-2flex-wrap">
<pclassName="font-boldtext-gray-800">{med.name}</p>
{med.active&&<spanclassName="text-xsbg-green-100text-green-700px-2py-0.5rounded-fullfont-medium">Aktiv</span>}
</div>
{med.dosage&&<pclassName="text-smtext-gray-600mt-0.5">Dosis:{med.dosage}</p>}
{med.frequency&&<pclassName="text-smtext-gray-500">{med.frequency}</p>}
{med.start_date&&(
<pclassName="text-xstext-gray-400mt-1">
Ab{newDate(med.start_date).toLocaleDateString(de-DE)}
{med.end_date&&`bis${newDate(med.end_date).toLocaleDateString(de-DE)}`}
</p>
)}
{med.notes&&<pclassName="text-xstext-gray-400mt-1italic">{med.notes}</p>}
</div>
<divclassName="flexflex-colgap-2">
<button
onClick={()=>toggle(med)}
className={`text-xspx-3py-1.5rounded-lgfont-mediumtransition-colors${med.active?bg-gray-100text-gray-600hover:bg-gray-200:bg-green-100text-green-700hover:bg-green-200}`}
>
{med.active?Beenden:Reaktivieren}
</button>
<buttononClick={()=>del(med.id)}className="text-xspx-3py-1.5rounded-lgtext-red-400hover:bg-red-50transition-colors">Löschen</button>
</div>
</div>
</div>
)

return(
<divclassName="min-h-screen">
<Header/>
<mainclassName="max-w-2xlmx-autopx-4py-6">
<divclassName="flexitems-centerjustify-betweenmb-6">
<divclassName="flexitems-centergap-3">
<Linkhref="/dashboard"className="text-gray-400hover:text-gray-600">†Zurück</Link>
<h1className="text-xlfont-boldtext-gray-800">ðŸ’ŠMedikamente</h1>
</div>
<buttononClick={()=>setShowForm(s=>!s)}className="btn-primarytext-sm">+Neu</button>
</div>

{/*Addform*/}
{showForm&&(
<divclassName="cardp-5mb-5">
<pclassName="font-boldtext-gray-800mb-4">NeuesMedikament</p>
<divclassName="space-y-3">
<div>
<labelclassName="label">Name*</label>
<inputtype="text"value={form.name}onChange={e=>setForm(f=>({...f,name:e.target.value}))}placeholder="z.B.Metronidazol,Fortiflora,Panacur"className="input-field"/>
</div>
<divclassName="gridgrid-cols-2gap-3">
<div>
<labelclassName="label">Dosis</label>
<inputtype="text"value={form.dosage}onChange={e=>setForm(f=>({...f,dosage:e.target.value}))}placeholder="z.B.0,5ml"className="input-field"/>
</div>
<div>
<labelclassName="label">Häufigkeit</label>
<selectvalue={form.frequency}onChange={e=>setForm(f=>({...f,frequency:e.target.value}))}className="input-field">
<optionvalue="">Wählen</option>
{FREQUENCIES.map(f=><optionkey={f}value={f}>{f}</option>)}
</select>
</div>
</div>
<divclassName="gridgrid-cols-2gap-3">
<div>
<labelclassName="label">Start</label>
<inputtype="date"value={form.start_date}onChange={e=>setForm(f=>({...f,start_date:e.target.value}))}className="input-field"/>
</div>
<div>
<labelclassName="label">Ende</label>
<inputtype="date"value={form.end_date}onChange={e=>setForm(f=>({...f,end_date:e.target.value}))}className="input-field"/>
</div>
</div>
<div>
<labelclassName="label">Notiz</label>
<inputtype="text"value={form.notes}onChange={e=>setForm(f=>({...f,notes:e.target.value}))}placeholder="z.B.insFuttermischen"className="input-field"/>
</div>
<divclassName="flexgap-2pt-1">
<buttononClick={()=>setShowForm(false)}className="btn-secondary">Abbrechen</button>
<buttononClick={save}disabled={!form.name||saving}className="btn-primary">{saving?Speichern:Speichern}</button>
</div>
</div>
</div>
)}

{loading?(
<divclassName="space-y-3">{Array.from({length:2}).map((_,i)=><divkey={i}className="h-24bg-gray-100rounded-2xlanimate-pulse"/>)}</div>
):(
<>
{active.length===0&&inactive.length===0&&(
<divclassName="cardp-10text-center">
<divclassName="text-5xlmb-3">ðŸ’Š</div>
<pclassName="text-gray-500mb-1">KeineMedikamenteeingetragen</p>
<pclassName="text-smtext-gray-400">Tippeaufž+Neu"umeinMedikamenthinzuzufügen</p>
</div>
)}

{active.length>0&&(
<divclassName="space-y-3mb-5">
<h2className="text-smfont-semiboldtext-gray-500uppercasetracking-wide">AktiveMedikamente</h2>
{active.map(m=><MedCardkey={m.id}med={m}/>)}
</div>
)}

{inactive.length>0&&(
<divclassName="space-y-3">
<h2className="text-smfont-semiboldtext-gray-400uppercasetracking-wide">Abgeschlossen</h2>
{inactive.map(m=><MedCardkey={m.id}med={m}/>)}
</div>
)}
</>
)}
</main>
</div>
)
}
